apiVersion: v1
kind: Service
metadata:
  name: rc-recommender
  labels:
    app: rc-recommender
spec:
  type: LoadBalancer
  selector:
    app: rc-recommender
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
